"""Not the jpipe-runner 3 authoring API: importing this package says what replaced it.

Every step library written for v3, and every one the jPipe compiler generated up to 2.5.0,
starts by importing ``jpipe_runner.framework.decorators``. This stub turns the bare
``ModuleNotFoundError`` those imports would raise into instructions (ADR-0006, #140).
"""

raise ImportError(
    "jpipe_runner.framework is the jpipe-runner 3 authoring API, which jpipe-runner 4 "
    "replaced. Import from jpipe_runner instead: @evidence, @strategy, @sub_conclusion "
    "and @conclusion replace @jpipe and @jpipe_link, and a step returns Pass(), "
    "Fail(reason) or Skip(reason) instead of True or False. A step library generated by "
    "jPipe 2.5.0 or earlier is written for jpipe-runner 3: run it with jpipe-runner<4, "
    "or update it by hand.",
    name=__name__,
)
