import re
import sys
try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]  # backport for Python < 3.11
    except ImportError as exc:
        raise ImportError(
            "Python ≥ 3.11 is required (tomllib is stdlib since 3.11), "
            "or install: pip install tomli"
        ) from exc
from pathlib import Path

from setuptools import find_packages, setup


def _parse_author(entry: str) -> tuple[str, str]:
    """Parse 'Name <email@example.com>' into (name, email)."""
    match = re.search(r"^(.*?)\s*<([^>]+)>$", entry.strip())
    if match:
        return match.group(1).strip(), match.group(2).strip()
    return entry.strip(), ""


def _read_requirements(filepath: str = "requirements.txt") -> list[str]:
    """Read install_requires from a requirements.txt generated by poetry export."""
    path = Path(filepath)
    if not path.exists():
        return []
    return [
        line.split(";")[0].rstrip("\\").strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith(("--", "#"))
    ]


with open("pyproject.toml", "rb") as _f:
    _pyproject = tomllib.load(_f)

_poetry = _pyproject["tool"]["poetry"]

_authors = [_parse_author(a) for a in _poetry.get("authors", [])]
_names = ", ".join(name for name, _ in _authors)
_emails = ", ".join(email for _, email in _authors if email)

_packages_from = (_poetry.get("packages") or [{}])[0].get("from", "")

config = {
    "name": _poetry["name"],
    "version": _poetry["version"],
    "description": _poetry["description"],
    "url": _poetry.get("homepage", ""),
    "license": _poetry.get("license", ""),
    "author": _names,
    "author_email": _emails,
    "classifiers": _poetry.get("classifiers", []),
    "keywords": _poetry.get("keywords", []),
    "install_requires": _read_requirements(),
    "extras_require": _poetry.get("extras", {}),
    "python_requires": _poetry["dependencies"]["python"],
    "long_description": Path(_poetry["readme"]).read_text(encoding="utf-8"),
    "long_description_content_type": "text/markdown",
    "packages": find_packages(where=_packages_from) if _packages_from else find_packages(),
    "package_dir": {"": _packages_from} if _packages_from else {},
    "entry_points": {
        "console_scripts": [
            f"{name} = {script}" for name, script in _poetry.get("scripts", {}).items()
        ]
    },
    "include_package_data": True,
}

if config["name"] == "jpipe-runner":
    config["scripts"] = ["bin/jpipe-runner"]

if __name__ == "__main__" and len(sys.argv) > 1 and sys.argv[1] == "--print-config":
    print("=== Setup.py Configuration Values ===")
    for key, value in config.items():
        print(f"{key.replace('_', ' ').title()}: {value}")
    print("=====================================")

setup(**config)
