name: JPipe Runner - Vanilla demonstration

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  jpipe-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Justify Slides
        uses: "jpipe-mcscert/jpipe-runner@build/release-pipeline"
        with:
          jd_file: "examples/models/01_slides.json"
          variable: |
            signature:jason
            available:ready
          library: |
            examples/libraries/slides.py
          version: "build/release-pipeline"
