name: JPipe Runner - Poetry demonstration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - feat/v2

jobs:

  jpipe-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "latest"

      - name: Create/Set up Poetry environment
        run: |
          cd examples
          poetry init -n
          poetry config virtualenvs.in-project true
          poetry add rich

      - name: Justify Notebook Quality
        uses: "jpipe-mcscert/jpipe-runner@f27686da4e896bb86b46845303fe64dae12631e8"
        with:
          jd_file: "models/02_quality_full.jd.json"
          python_path: "poetry run python"
          working_directory: "./examples"
          variable: |
            notebook:notebook.ipynb
          library: |
            libraries/notebook.py
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: "f27686da4e896bb86b46845303fe64dae12631e8"
