name: JPipe Runner - Vanilla demonstration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - feat/v2

jobs:
  jpipe-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Justify Slides
        uses: "jpipe-mcscert/jpipe-runner@build/release-pipeline"
        with:
          jd_file: "examples/models/01_slides.json"
          variable: |
            signature:jason
            available:ready
          library: |
            examples/libraries/slides.py
          github_token: ${{ secrets.GITHUB_TOKEN }}
