name: Test Action

on:
  pull_request:
    branches:
      - main
      - dev
permissions:
  contents: write
  pull-requests: write

jobs:
  test-simple-success:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/test-template.yml
    with:
      working_directory: 'tests/action/resources/simple_success'
      jd_file: 'file_validation.json'
      library: 'file_validation.py'
      config-file: 'config.yaml'
      expected_result: '0'
    secrets: inherit

  test-missing-consumer:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/test-template.yml
    with:
      working_directory: 'tests/action/resources/missing_consumer'
      jd_file: 'math_operation.json'
      library: 'math_operation.py'
      expected_result: '1'
    secrets: inherit
