name: Test Template

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      jd_file:
        required: true
        type: string
      library:
        required: true
        type: string
      config-file:
        required: false
        type: string
        default: ''
      expected_result:
        required: false
        type: string
        default: '0'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run jPipe Runner Action
        id: run_jpipe
        uses: ./
        continue-on-error: true
        with:
          working_directory: ${{ inputs.working_directory }}
          jd_file: ${{ inputs.jd_file }}
          library: ${{ inputs.library }}
          config-file: ${{ inputs.config-file }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check expected result
        run: |
          if [ "${{ steps.run_jpipe.outputs.result }}" != "${{ inputs.expected_result }}" ]; then
            exit 1
          fi
